### ISSUE TITLE
Assertion Error and endless loop conditions

### ISSUE THREAD

**Issue by jspv** [spyder-ide/three-merge#10]
The following demonstrates a failure to merge:

python -c 'import merge; print(merge.merge("abcdef","abde","abcde"))'

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/test/merge.py", line 230, in merge
    assert target_status == ADDITION or source_status == PRESERVED
AssertionError

The following results in an endless loop:

python -c 'import merge; print(merge.merge("abcdef","abd","abcde"))'

Python 3.9.1
diff-match-patch==20200713

**Comment by CookieDragonX** [comment]
Hello,
In merge.py, line 230:
"assert target_status == ADDITION or **source_status** == PRESERVED"
should be modified as:
"assert target_status == ADDITION or **target_status**== PRESERVED"
For example mentioned above - merge("abcdef","abde","abcde")
with this change, function provides expected output "abdef"
